figures_dir:
  "/var/www/html/genotyping_figures/"

pangenie_path:
  "/usr/local/bin/PanGenie"

read_length:
  150


k:
  31

n_threads:
  16

n_threads_data:
  40

n_threads_data_quarter:
  25

hg38_2bit_file:
  #"https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit"
  "http://ivarg.ddns.net/hg38.2bit"

random_seed:
  1

chromosomes:
  "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"

thousand_genomes_vcf:
  "http://ivarg.ddns.net/variants.vcf.gz"

sv_vcf:
    "https://s3-us-west-1.amazonaws.com/illumina-polaris-v2.1-sv-truthset/all_merge.vcf.gz"

analysis_regions:
  simulated_dataset0:
    region: "1:1-1000000"
    genome_size: "1000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000"
    vcf: "simulated_vcf"
    n_variants: 300
    n_individuals: 500

  simulated_dataset1:
    region: "1:1-3000000"
    genome_size: "3000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "10000"
    vcf: "simulated_vcf"
    n_variants: 1000
    n_individuals: 500

  simulated_dataset2:
    region: "1:1-10000000"
    genome_size: "10000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "300000"
    vcf: "simulated_vcf"
    n_variants: 40000
    n_individuals: 1000

  simulated_dataset4:
    region: "1:1-75000000"
    genome_size: "75000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "40000"
    vcf: "simulated_vcf"
    n_variants: 10000
    n_individuals: 1000

  dataset1:
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"
    vcf: "thousand_genomes_vcf"
  dataset2:
    region: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    genome_size: "3031000000"
    #chromosomes: "1 2 3 3 4 4 5 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    simulation_chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22"
    n_nodes: "84000000"
    vcf: "thousand_genomes_vcf"

  # only chr 1
  dataset3:
    region: "1:1-248956422"
    genome_size: "248956422"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "10000000"
    vcf: "thousand_genomes_vcf"

  # chr 1-3
  dataset4:
    region: "1 2 3"
    genome_size: "689445510"
    chromosomes: "1 2 3"
    simulation_chromosomes: "1 2 3"
    n_nodes: "30000000"
    vcf: "thousand_genomes_vcf"

  dataset5:
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"
    vcf: "thousand_genomes_vcf"
    only_snps: True

  svdataset1:
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"
    skip_individuals: "NA12889"

  svdataset2:
    region: "1:1-50000000"
    genome_size: "50000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "50000000"
    skip_individuals: "NA12889"


truth_datasets:
  hg002:
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv3.3.2/GRCh38/HG002_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC-SOLIDgatkHC_CHROM1-22_v.3.3.2_highconf_triophased.vcf.gz"
    regions_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG002_NA24385_son/NISTv3.3.2/GRCh38/HG002_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC-SOLIDgatkHC_CHROM1-22_v.3.3.2_highconf_noinconsistent.bed"
    #reads_url: "http://ivarg.ddns.net/HG002run1_s1_testsample_v2.bam"
    reads_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/NIST_HiSeq_HG002_Homogeneity-10953946/HG002Run01-11419412/HG002run1_S1.bam"

  hg003:
    reads_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG003_NA24149_father/NIST_HiSeq_HG003_Homogeneity-12389378/HG003Run01-13262252/HG003Run01_S1.bam"
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG003_NA24149_father/NISTv3.3.2/GRCh38/HG003_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf.vcf.gz"
    regions_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG003_NA24149_father/NISTv3.3.2/GRCh38/HG003_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf_noinconsistent.bed"

  hg004:
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG004_NA24143_mother/NISTv3.3.2/GRCh38/HG004_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf.vcf.gz"
    reads_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG004_NA24143_mother/NIST_HiSeq_HG004_Homogeneity-14572558/HG004Run01-15133132/HG004Run01_S1.bam"
    regions_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio/HG004_NA24143_mother/NISTv3.3.2/GRCh38/HG004_GRCh38_GIAB_highconf_CG-Illfb-IllsentieonHC-Ion-10XsentieonHC_CHROM1-22_v.3.3.2_highconf_noinconsistent.bed"

  #chinese trio father:
  hg006:
    vcf_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG006_NA24694_father/NISTv4.2.1/GRCh38/HG006_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"
    regions_url: "https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/ChineseTrio/HG006_NA24694_father/NISTv4.2.1/GRCh38/HG006_GRCh38_1_22_v4.2.1_benchmark.bed"
    reads_url: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/ChineseTrio/HG006_NA24694-huCA017E_father/NA24694_Father_HiSeq100x/NA24694_Father_HiSeq100x_fastqs/NA24694_Justin-18411395/NA24694_combined-19068141/NA24694-combined_S1.bam"

  NA12889:
    vcf_url: "https://s3-us-west-1.amazonaws.com/illumina-polaris-v2.1-sv-truthset/all_merge.vcf.gz"
    regions_url: "https://raw.githubusercontent.com/ivargr/genotyping-benchmarking/dev-sv/resources/grch38.bed"

    
    